#!/usr/bin/env bash
# e2e-mission.sh — run the REAL dsh harness against a SCRIPTED local model and
# assert that the seven-plugin engineering suite actually produced its
# artifacts.
#
# Why: the suite had never been verified with a live agent loop (no
# DEEPSEEK_API_KEY in the verification sandbox, and no budget for one). This
# script replaces only the token generator — `scripts/stub-llm.mjs` speaks the
# DeepSeek chat-completions SSE subset the adapter consumes — and keeps
# everything else real: the harness boot, tool dispatch, plugin hooks, the
# quality gate's subprocess, the mission store, the audit trail.
#
# usage: bash scripts/e2e-mission.sh [--no-build] [--keep] [--timeout SECONDS]
#   --no-build   reuse the existing packages/*/dist (default: build first)
#   --keep       do not wipe /tmp/dsh-e2e before writing the profile
#   --timeout    watchdog for the dsh run in seconds (default 300)
#
# SANDBOX: the run sets DSH_PERMISSION_MODE=danger-full-access for the child
# `dsh` unless $E2E_PERMISSION_MODE says otherwise. The verification sandbox is
# itself seatbelted, so a nested `sandbox-exec` fails with
# "sandbox_apply: Operation not permitted" and the *bash tool* refuses to run
# unconfined ("no sandbox backend is usable on this host; … otherwise switch
# the consumer to danger-full-access"). The harness's own error message names
# this remedy; the workspace here is a throwaway /tmp scratch repo whose only
# commands are `node --test` / `node -e`. Set E2E_PERMISSION_MODE=workspace-write
# to see the refusal instead (the flow then fails loudly, by design).
#
# Everything it creates lives under $E2E_HOME (default /tmp/dsh-e2e); nothing
# outside it is written. Re-runnable: the profile, the workspace and the stub
# script are rebuilt from scratch on every run.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
E2E_HOME="${E2E_HOME:-/tmp/dsh-e2e}"
PORT="${STUB_PORT:-8787}"
BASE_URL="http://127.0.0.1:${PORT}/v1"
PROFILE="headless"
WS="$E2E_HOME/ws"
LOGS="$E2E_HOME/logs"
STUB_LOG="$LOGS/stub-llm.log"
DSH_LOG="$LOGS/dsh.log"
TIMEOUT_SECONDS=300
DO_BUILD=1
KEEP=0
PERMISSION_MODE="${E2E_PERMISSION_MODE:-danger-full-access}"

# The seven plugins under verification (dsh-eng-core is a library dependency,
# linked but not a bundle).
SUITE=(
  dsh-role-guard
  dsh-spec-gate
  dsh-test-design-gate
  dsh-quality-gate
  dsh-evidence-gate
  dsh-audit-trail
  dsh-orchestrator
)

while [ $# -gt 0 ]; do
  case "$1" in
    --no-build) DO_BUILD=0; shift ;;
    --keep) KEEP=1; shift ;;
    --timeout) TIMEOUT_SECONDS="${2:-300}"; shift 2 ;;
    -h|--help) sed -n '2,22p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

FAILURES=0
pass() { printf '  \033[32mPASS\033[0m %s\n' "$*"; }
fail() { printf '  \033[31mFAIL\033[0m %s\n' "$*"; FAILURES=$((FAILURES + 1)); }
info() { printf '  ---- %s\n' "$*"; }
section() { printf '\n=== %s\n' "$*"; }

# ---------------------------------------------------------------------------
# 1. build the suite
# ---------------------------------------------------------------------------
section "1/6 build the suite"
if [ "$DO_BUILD" = "1" ]; then
  bash "$ROOT/scripts/build-all.sh"
else
  info "--no-build: reusing packages/*/dist"
fi

# ---------------------------------------------------------------------------
# 2. isolated DSH_HOME + profile (idempotent: wipe + recreate)
# ---------------------------------------------------------------------------
section "2/6 isolated profile under $E2E_HOME"
if [ "$KEEP" = "1" ]; then
  info "--keep: not wiping $E2E_HOME"
else
  rm -rf "$E2E_HOME"
fi
mkdir -p "$E2E_HOME/profiles/$PROFILE" "$E2E_HOME/profiles/node_modules" "$LOGS" "$WS"

# The launcher rewrites this file on every boot; it only anchors the loader.
printf '[]\n' > "$E2E_HOME/profiles/$PROFILE/cordis.yml"

node - "$E2E_HOME/profiles/$PROFILE/package.json" "${SUITE[@]}" <<'JS'
const fs = require('node:fs')
const [target, ...suite] = process.argv.slice(2)
const manifest = {
  name: 'dsh-profile-e2e-headless',
  private: true,
  dependencies: {},
  dsh: {
    profile: {
      bundles: ['@deepseek-ai/dsh-base', '@deepseek-ai/dsh-headless', ...suite],
      patchReload: 'startup',
    },
  },
}
fs.writeFileSync(target, `${JSON.stringify(manifest, null, 2)}\n`)
JS

# Profile patch layer: the documented §4 recipe (workspaces row + storage
# overrides) plus the overrides this verification needs. Each plugin keeps its
# own log inside $E2E_HOME — the defaults write to ~/.dsh, which is outside
# this run's sandbox boundary.
cat > "$E2E_HOME/profiles/$PROFILE/cordis.patch.yml" <<YAML
# Generated by scripts/e2e-mission.sh — do not edit by hand.
- config:
    - id: storage-json
      config:
        root: !!js dshHomePath('storages')

    - id: storage-domain
      config:
        backend: json

- insert:
    - id: workspace
      name: '@deepseek-ai/dsh-workspace'

# --- the isolated profile's own overrides -----------------------------------
# No human is attached to a headless run: the session-title LLM call would be a
# second, unscripted request, so it is switched off.
- id: session-title-llm
  disabled: true

- id: role-guard
  config: { logFile: '$LOGS/role-guard.log' }

# approval: auto — there is no approval channel in headless, so the spec would
# otherwise stay unapproved forever (and every write would be denied).
- id: spec-gate
  config: { logFile: '$LOGS/spec-gate.log', approval: auto, enforce: true }

- id: test-design-gate
  config: { logFile: '$LOGS/test-design-gate.log' }

# The command list is host configuration, never model input: one required
# command that passes, so the gate's verdict is a genuine, complete PASS.
- id: quality-gate
  config:
    logFile: '$LOGS/quality-gate.log'
    commands:
      - id: smoke
        name: 冒烟命令
        command: node -e "process.exit(0)"
        required: true
        phase: gate

- id: evidence-gate
  config: { logFile: '$LOGS/evidence-gate.log' }

- id: audit-trail
  config: { logFile: '$LOGS/audit-trail.log' }

- id: orchestrator
  config: { logFile: '$LOGS/orchestrator.log' }
YAML

# Module resolution: the shipped @deepseek-ai packages come from the real
# profile, the suite from this working tree. The launcher heals the rest.
ln -sfn "$HOME/.dsh/profiles/node_modules/@deepseek-ai" "$E2E_HOME/profiles/node_modules/@deepseek-ai"
for pkg in "${SUITE[@]}" dsh-eng-core; do
  ln -sfn "$ROOT/packages/$pkg" "$E2E_HOME/profiles/node_modules/$pkg"
done
info "profile: $E2E_HOME/profiles/$PROFILE (bundles: ${SUITE[*]})"

# ---------------------------------------------------------------------------
# 3. the scripted model
# ---------------------------------------------------------------------------
section "3/6 scripted model"
cat > "$E2E_HOME/script.json" <<'JSON'
{
  "steps": [
    {
      "tool": "orchestrate",
      "arguments": { "action": "stages" },
      "note": "probe: the orchestrator answers and lists the mounted suite"
    },
    {
      "tool": "spec_create",
      "arguments": {
        "title": "为 scratch 工作区添加 health 模块",
        "background": "端到端验证：真实 harness + 脚本化模型，证明七个插件在活会话里工作。",
        "requirements": [
          "src/health.mjs 导出 health()，返回 { status: 'ok' }",
          "test/health.test.mjs 用 node --test 覆盖 health()"
        ],
        "acceptanceCriteria": [
          "调用 health() 返回 { status: 'ok' }",
          "node --test test/health.test.mjs 退出码为 0"
        ],
        "fileBoundaries": ["src/**", "test/**"],
        "negativeConstraints": ["不得修改 .dsh/ 下的工程台账", "不得修改本仓库 packages/** 源码"],
        "testDesign": "### 正向场景\n\n| 用例ID | 前置条件 | 操作步骤 | 预期结果 | 覆盖验收标准 |\n|--------|----------|----------|----------|--------------|\n| TC-001 | 已安装 node | 运行 node -e \"import('./src/health.mjs').then(m => console.log(m.health()))\" | 退出码 0 且输出包含 status: ok | AC-001 |\n\n### 异常场景\n\n| 用例ID | 前置条件 | 操作步骤 | 预期结果 | 覆盖验收标准 |\n|--------|----------|----------|----------|--------------|\n| TC-002 | 模块被改名 | 运行 node --test test/health.test.mjs | 退出码非 0 且 stderr 报模块解析失败 | AC-002 |\n\n### 边界场景\n\n| 用例ID | 前置条件 | 操作步骤 | 预期结果 | 覆盖验收标准 |\n|--------|----------|----------|----------|--------------|\n| TC-003 | 重复调用 health() | 连续调用两次并比较返回值 | 两次都是 status: ok 且互不共享可变状态 | AC-001 |\n"
      },
      "note": "spec-gate: create the specification and bind the session's mission"
    },
    {
      "tool": "test_design_review",
      "arguments": {},
      "expectResultContains": ["测试设计评审通过"],
      "note": "test-design-gate: the three scenario classes must pass review"
    },
    {
      "tool": "write",
      "arguments": { "file_path": "src/health.mjs", "content": "export const health = () => ({ status: 'ok' })\n" },
      "expectResultContains": ["尚未审批"],
      "note": "probe: a write BEFORE approval must be refused by spec-gate"
    },
    {
      "tool": "spec_approve",
      "arguments": { "note": "测试设计已通过，规格可审批（headless: approval=auto）" },
      "note": "spec-gate: approval unlocks the write tools"
    },
    {
      "tool": "write",
      "arguments": { "file_path": "src/health.mjs", "content": "export const health = () => ({ status: 'ok' })\n" },
      "note": "the implementation file, written by the real write tool"
    },
    {
      "tool": "write",
      "arguments": {
        "file_path": "test/health.test.mjs",
        "content": "import assert from 'node:assert/strict'\nimport test from 'node:test'\nimport { health } from '../src/health.mjs'\n\ntest('health() reports ok', () => {\n    assert.deepEqual(health(), { status: 'ok' })\n})\n"
      },
      "note": "the node --test case the acceptance criteria name"
    },
    {
      "tool": "bash",
      "arguments": { "command": "node --test test/health.test.mjs", "description": "Run the health module test" },
      "expectResultContains": ["pass 1"],
      "note": "real bash tool: the next request asserts this result really carries the test output"
    },
    {
      "tool": "evidence_record",
      "arguments": {
        "kind": "test",
        "summary": "node --test test/health.test.mjs: 1 passed",
        "command": "node --test test/health.test.mjs",
        "exitCode": 0,
        "output": "ok 1 - health() reports ok\n# tests 1\n# pass 1\n# fail 0"
      },
      "note": "evidence-gate: a successful test row (required kind)"
    },
    {
      "tool": "bash",
      "arguments": {
        "command": "node -e \"import('./src/health.mjs').then(m => console.log('health status =', m.health().status))\"",
        "description": "Call health() and print its status"
      },
      "expectResultContains": ["health status = ok"],
      "note": "real bash tool: an independent check of AC-001"
    },
    {
      "tool": "evidence_record",
      "arguments": {
        "kind": "command",
        "summary": "import('./src/health.mjs').then(...): health status = ok",
        "command": "node -e \"import('./src/health.mjs').then(m => console.log('health status =', m.health().status))\"",
        "exitCode": 0,
        "output": "health status = ok"
      },
      "note": "evidence-gate: a successful command row (required kind)"
    },
    {
      "tool": "quality_gate_run",
      "arguments": { "reason": "交付前跑宿主配置的门禁命令" },
      "expectResultContains": ["PASS"],
      "note": "quality-gate: the host-configured smoke command decides the verdict"
    },
    {
      "tool": "mission_complete",
      "arguments": { "summary": "health 模块与用例已交付（e2e-mission.sh）" },
      "expectResultContains": ["✅"],
      "note": "evidence-gate: issue the immutable receipt"
    },
    {
      "say": "health 模块与 node --test 用例已实现，测试与门禁均通过，mission 已交付并签发回执。",
      "note": "the only text-only turn: the agent loop stops here"
    }
  ]
}
JSON

STUB_SCRIPT="$E2E_HOME/script.json" node "$ROOT/scripts/stub-llm.mjs" --check >/dev/null
info "script: $E2E_HOME/script.json (14 steps, validated)"

STUB_PID=""
cleanup() {
  if [ -n "$STUB_PID" ] && kill -0 "$STUB_PID" 2>/dev/null; then
    kill -TERM "$STUB_PID" 2>/dev/null || true
    wait "$STUB_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

STUB_SCRIPT="$E2E_HOME/script.json" STUB_PORT="$PORT" node "$ROOT/scripts/stub-llm.mjs" >"$STUB_LOG" 2>&1 &
STUB_PID=$!

ready=0
for _ in $(seq 1 50); do
  if node -e "fetch('http://127.0.0.1:${PORT}/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))" 2>/dev/null; then
    ready=1
    break
  fi
  sleep 0.2
done
if [ "$ready" != "1" ]; then
  fail "stub-llm did not become healthy on 127.0.0.1:$PORT"
  sed -n '1,40p' "$STUB_LOG" >&2 || true
  exit 1
fi
pass "stub-llm healthy on 127.0.0.1:$PORT (pid $STUB_PID)"

# ---------------------------------------------------------------------------
# 4. scratch workspace (git — the quality/evidence gates take the git path)
# ---------------------------------------------------------------------------
section "4/6 scratch workspace"
(
  cd "$WS"
  git init -q
  git config user.email "e2e@example.com"
  git config user.name "dsh e2e"
  git config commit.gpgsign false
  printf '# e2e scratch workspace\n\nCreated by scripts/e2e-mission.sh.\n' > README.md
  git add -A
  git commit -qm "chore: scratch workspace"
)
info "workspace: $WS ($(cd "$WS" && git rev-parse --short HEAD) on $(cd "$WS" && git rev-parse --abbrev-ref HEAD))"

# ---------------------------------------------------------------------------
# 5. run the real harness against the stub
# ---------------------------------------------------------------------------
section "5/6 dsh --profile $PROFILE against the stub"
info "sandbox mode for the child run: $PERMISSION_MODE (see the SANDBOX note in this script's header)"
TASK="在 src/health.mjs 实现 health() 模块并补上 node --test 用例，然后按工程套件的流程交付。"

DSH_PID=""
watchdog() {
  sleep "$TIMEOUT_SECONDS"
  if kill -0 "$DSH_PID" 2>/dev/null; then
    echo "e2e-mission: WATCHDOG fired after ${TIMEOUT_SECONDS}s — killing dsh (pid $DSH_PID)" >&2
    kill -TERM "$DSH_PID" 2>/dev/null || true
    sleep 2
    kill -KILL "$DSH_PID" 2>/dev/null || true
  fi
}

set +e
(
  cd "$WS"
  DSH_HOME="$E2E_HOME" \
  DEEPSEEK_BASE_URL="$BASE_URL" \
  DEEPSEEK_API_KEY="stub-key-not-a-secret" \
  DEEPSEEK_ALLOW_INSECURE_HTTP=1 \
  DSH_PERMISSION_MODE="$PERMISSION_MODE" \
  dsh --profile "$PROFILE" "$TASK"
) >"$DSH_LOG" 2>&1 &
DSH_PID=$!
watchdog &
WATCHDOG_PID=$!
wait "$DSH_PID"
DSH_RC=$?
kill "$WATCHDOG_PID" 2>/dev/null || true
wait "$WATCHDOG_PID" 2>/dev/null || true
DSH_PID=""
set -e

info "dsh exit code: $DSH_RC"
info "dsh stdout/stderr: $(wc -l < "$DSH_LOG" | tr -d ' ') lines → $DSH_LOG"

# ---------------------------------------------------------------------------
# 6. assertions
# ---------------------------------------------------------------------------
section "6/6 assertions"

STUB_FATALS="$(grep -c 'STUB-FATAL' "$STUB_LOG" || true)"
if [ "$STUB_FATALS" = "0" ]; then
  pass "stub served every request without a protocol/script violation"
else
  fail "stub reported $STUB_FATALS STUB-FATAL line(s) — see $STUB_LOG"
fi
info "stub decisions: $(grep -c 'DECIDE' "$STUB_LOG" || true) (expected 14)"

if [ "$DSH_RC" = "0" ]; then
  pass "dsh exited 0"
else
  fail "dsh exited $DSH_RC"
fi

DOT="$WS/.dsh"
MISSION_JSON="$(ls -t "$DOT"/missions/*/mission.json 2>/dev/null | head -1 || true)"
if [ -n "$MISSION_JSON" ]; then
  MISSION_DIR="$(dirname "$MISSION_JSON")"
  MISSION_ID="$(basename "$MISSION_DIR")"
  pass "mission record exists: .dsh/missions/$MISSION_ID/mission.json"
else
  MISSION_ID=""
  fail "no .dsh/missions/*/mission.json"
fi

read_field() { # read_field <file> <js-expression over `m`>
  node -e "const m=require(process.argv[1]);const v=($2);process.stdout.write(v===undefined?'':String(v))" "$1" 2>/dev/null || true
}

if [ -n "$MISSION_ID" ]; then
  SPEC="$DOT/specs/$MISSION_ID.md"
  if [ -f "$SPEC" ]; then
    if grep -q 'AC-001' "$SPEC" && grep -q '## 验收标准' "$SPEC"; then
      pass "spec artifact .dsh/specs/$MISSION_ID.md carries the acceptance criteria"
    else
      fail "spec artifact exists but carries no 验收标准 / AC-001"
    fi
  else
    fail "spec artifact .dsh/specs/$MISSION_ID.md is missing"
  fi

  STATUS="$(read_field "$MISSION_JSON" 'm.status')"
  case "$STATUS" in
    delivered|completed|retrospected|closed) pass "mission status: $STATUS" ;;
    *) fail "mission status is '$STATUS' (expected delivered or later)" ;;
  esac

  APPROVED_AT="$(read_field "$MISSION_JSON" 'm.spec && m.spec.approvedAt')"
  if [ -n "$APPROVED_AT" ]; then
    pass "spec.approvedAt recorded (by $(read_field "$MISSION_JSON" 'm.spec && m.spec.approvedBy'))"
  else
    fail "spec.approvedAt missing — the specification was never approved"
  fi

  DESIGN_PASSED="$(read_field "$MISSION_JSON" 'm.testDesign && m.testDesign.passed')"
  DESIGN_CASES="$(read_field "$MISSION_JSON" 'm.testDesign && m.testDesign.cases && m.testDesign.cases.length')"
  if [ "$DESIGN_PASSED" = "true" ]; then
    pass "testDesign.passed === true ($DESIGN_CASES cases)"
  else
    fail "testDesign.passed is '$DESIGN_PASSED' (expected true)"
  fi

  GATE_FILE="$(grep -rl '"state": *"PASS"' "$MISSION_DIR/gates" 2>/dev/null | head -1 || true)"
  if [ -n "$GATE_FILE" ]; then
    GATE_FULL="$(read_field "$GATE_FILE" 'm.scope && m.scope.full')"
    GATE_RESULTS="$(read_field "$GATE_FILE" 'm.results && m.results.length')"
    if [ "$GATE_FULL" = "true" ] && [ "$GATE_RESULTS" != "0" ] && [ -n "$GATE_RESULTS" ]; then
      pass "gate $(basename "$GATE_FILE"): state PASS, scope.full === true, $GATE_RESULTS result(s)"
    else
      fail "gate $(basename "$GATE_FILE") is PASS but scope.full=$GATE_FULL results=$GATE_RESULTS"
    fi
  else
    fail "no gates/*.json with state PASS"
  fi

  RECEIPT="$(find "$MISSION_DIR/receipts" -name 'RCP-*.json' 2>/dev/null | head -1 || true)"
  if [ -n "$RECEIPT" ]; then
    pass "receipt $(basename "$RECEIPT") issued"
  else
    fail "no receipts/RCP-*.json — the mission was not delivered"
  fi

  RETRO="$(find "$MISSION_DIR" -maxdepth 1 -name 'retrospective.json' 2>/dev/null | head -1 || true)"
  if [ -n "$RETRO" ]; then
    pass "retrospective.json exists ($(wc -c < "$RETRO" | tr -d ' ') bytes)"
  else
    info "retrospective.json absent — expected: this run drives the tools directly, not the orchestrator pipeline"
  fi
fi

AUDIT_FILE="$(find "$DOT/audit" -maxdepth 1 -name '*.jsonl' 2>/dev/null | head -1 || true)"
if [ -n "$AUDIT_FILE" ]; then
  PRE_ROWS="$(grep -c '"phase":"pre"' "$AUDIT_FILE" || true)"
  RESULT_ROWS="$(grep -c '"phase":"result"' "$AUDIT_FILE" || true)"
  if [ "$PRE_ROWS" -gt 0 ] && [ "$RESULT_ROWS" -gt 0 ]; then
    pass "audit trail $(basename "$AUDIT_FILE"): $PRE_ROWS pre / $RESULT_ROWS result rows"
  else
    fail "audit trail has pre=$PRE_ROWS result=$RESULT_ROWS (expected both > 0)"
  fi
  # The pre-approval write is the ONE expected failure: seeing it in the audit
  # trail is how this run proves the write guard really fired live. Any other
  # errored tool call is a regression the artifact assertions would not catch.
  AUDIT_ERRORS="$(node -e '
const fs = require("node:fs")
const rows = fs.readFileSync(process.argv[1], "utf8").trim().split("\n").map((line) => JSON.parse(line))
const errors = rows.filter((row) => row.phase === "result" && row.isError === true).map((row) => row.tool)
process.stdout.write(errors.join(","))
' "$AUDIT_FILE" 2>/dev/null || true)"
  if [ "$AUDIT_ERRORS" = "write" ]; then
    pass "audit trail: exactly one errored tool call (write before approval) — every other tool succeeded"
  else
    fail "audit trail errored tool calls: '${AUDIT_ERRORS:-<none>}' (expected exactly 'write')"
  fi
else
  fail "no .dsh/audit/*.jsonl"
fi

for file in src/health.mjs test/health.test.mjs; do
  if [ -f "$WS/$file" ] && grep -q 'health' "$WS/$file"; then
    pass "the write tool really wrote $file"
  else
    fail "$file missing or empty — the write tool did not write it"
  fi
done

MOUNTED=0
for pkg in "${SUITE[@]}"; do
  # The profile overrides name each log by its entry id, which is the short
  # name (dsh-spec-gate → spec-gate.log). "applied (" is the plugin's own
  # mount line — a file that merely exists proves nothing.
  if grep -q 'applied (' "$LOGS/${pkg#dsh-}.log" 2>/dev/null; then MOUNTED=$((MOUNTED + 1)); fi
done
if [ "$MOUNTED" = "${#SUITE[@]}" ]; then
  pass "all ${#SUITE[@]} plugins logged their own 'applied (' mount line under $LOGS"
else
  fail "only $MOUNTED/${#SUITE[@]} plugins logged an 'applied (' mount line under $LOGS"
fi

# ---------------------------------------------------------------------------
# summary
# ---------------------------------------------------------------------------
section "summary"
if [ "$FAILURES" = "0" ]; then
  printf '  \033[32mE2E GREEN\033[0m — the seven plugins ran a real mission in a live dsh session.\n'
  printf '  artifacts: %s\n' "$DOT"
  printf '  logs:      %s\n' "$LOGS"
  exit 0
fi

printf '  \033[31mE2E RED\033[0m — %s assertion(s) failed.\n' "$FAILURES"
if [ "${STUB_FATALS:-0}" != "0" ]; then
  printf '\n  \033[33mNOTE\033[0m the stub itself failed %s expectation/protocol check(s): this is a STUB\n' "$STUB_FATALS"
  printf '       mismatch (the scripted model did not see what it expected), not a harness\n'
  printf '       failure. The dsh TRANSPORT error below is the consequence of the stub\n'
  printf '       exiting to make the divergence loud. Fix the script/expectation, or read the\n'
  printf '       STUB-FATAL detail to see which harness behaviour actually differed.\n'
  grep -A 6 'STUB-FATAL' "$STUB_LOG" | head -30 || true
fi
printf '\n  --- stub-llm.log (tail) ---\n'
tail -n 40 "$STUB_LOG" || true
printf '\n  --- dsh.log (tail) ---\n'
tail -n 60 "$DSH_LOG" || true
exit 1
